DROP TABLE IF EXISTS Account CASCADE;

CREATE TABLE Account (
    ID SERIAL PRIMARY KEY,
    Email CHARACTER VARYING(255) UNIQUE NOT NULL,
    Password CHARACTER VARYING(255) NOT NULL,
    CreatedAt TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
